import {
    Handshake,
    Lock,
    Camera,
    ShoppingBag,
    Globe,
    Instagram,
    Youtube,
    Facebook,
    Twitter,
    Linkedin,
    Music,
    Video,
    Gamepad2,
    Briefcase,
    Heart,
    Star,
    Zap,
    Gift,
    DollarSign,
    CreditCard,
    Smartphone,
    Mail,
    MapPin,
    Calendar,
    Book,
    Coffee,
    Smile,
    Tag,
    TrendingUp,
    User
} from "lucide-react"

export const iconMap: Record<string, any> = {
    "Handshake": Handshake,
    "Lock": Lock,
    "Camera": Camera,
    "ShoppingBag": ShoppingBag,
    "Globe": Globe,
    "Instagram": Instagram,
    "Youtube": Youtube,
    "Facebook": Facebook,
    "Twitter": Twitter,
    "Linkedin": Linkedin,
    "Music": Music,
    "Video": Video,
    "Gamepad2": Gamepad2,
    "Briefcase": Briefcase,
    "Heart": Heart,
    "Star": Star,
    "Zap": Zap,
    "Gift": Gift,
    "DollarSign": DollarSign,
    "CreditCard": CreditCard,
    "Smartphone": Smartphone,
    "Mail": Mail,
    "MapPin": MapPin,
    "Calendar": Calendar,
    "Book": Book,
    "Coffee": Coffee,
    "Smile": Smile,
    "Tag": Tag,
    "TrendingUp": TrendingUp,
    "User": User
}

export const iconOptions = Object.keys(iconMap)
